### PR TITLE
Some user facing niceties

### PR DESCRIPTION
**Pull request by mcrmonkey**
see commits for detail on whats changed
authorJS made to work and cleaned up
Vote on post or comment text updated

Kicker on this was tests and forgetting code formatting which should now be accounted for.

### CODE REVIEW

**Comment by pjuu** [comment]
Awesome man. Just a few things.

I think "comment" is misleading. I changed it to "reply" in most cases and I think this is cleaner as realistically posts and replies are the same thing one just has a "reply_to" and isn't shown on a feed or your posts list.

Also the I know the disabling of the button was a bit redundant as the maxlength argument stops you typing more.

What are your thoughts?

Looks good though :+1:

**Comment by pjuu** [comment]
Can you also please squash the commits. I think that is the best way. I'll ensure all the ones I do this way will be squashed also.

**Comment by mcrmonkey** [comment]
attempted squash.
may have done it wrong though which has produced the merge.
Reading about probably shouldn't have done the merge after the fact. At least that's my interpretation any how. What say you?

**Comment by pjuu** [comment]
I'll merge this any how. I will write a wiki on how to perform the squash nicely, its been a while.

**Pull request merged**
