### PR TITLE
Added guidelines for GH

### PR DESCRIPTION
**Pull request by mcrmonkey**
+ Added template for new issues in GH
+ Added some contributing guidelines

### CODE REVIEW

**Comment by docapotamus** [comment]
The issue template... Most are not related to people running Pjuu.

**Comment by mcrmonkey** [comment]
You can delete that and replace it with something else and its only a guideline and doesn't HAVE to say that
most of what is open now are enhancements any how

**Comment by johnnynull** [comment]
Helpful stuff! Thanks!

**Comment by docapotamus** [comment]
I'll merge this in and we can look

**Pull request merged**
