### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by docapotamus**

### CODE REVIEW

**Comment by mcrmonkey** [comment]
@docapotamus  ?

**Comment by mcrmonkey** [comment]
@docapotamus is this needed ?

**Comment by docapotamus** [comment]
@mcrmonkey Nothing here is a security alert. I think the fix is unnecessary, as we are working on Pjuu 2.

**Comment by docapotamus** [comment]
@mcrmonkey Right I fixed the issue with Redis Py change.

Will try and merge this in tomorrow. Don't have time tonight to get this deployed out.

**Pull request merged**
