### PR TITLE
Implement new authentication layout

### PR DESCRIPTION
**Pull request by psgs**
Hello!

This pull request implements a new layout for the authentication pages that has been described in issue #93. The following is a short GIF of the new layout in action.

pjuulogin

Thanks for keeping Pjuu awesome,
psgs :palm_tree:

### CODE REVIEW

**Comment by pjuu** [comment]
Wow! This looks amazing :-) taking a look now. There are one or two tiny little issues but other than that this is bloody awesome!

**Comment by pjuu** [comment]
@mcrmonkey comments? Not sure how you checkout a PR through CLI but you can check it out via Github for Mac.

**Comment by mcrmonkey** [comment]
@joe yeah seen it. looks okay to me.

**Comment by pjuu** [comment]
Right I will merge this in now in that case. There are some issues with IE9 and a couple of usability things that I will address after the work on the UI enhancements. I will also clean up a couple of spacing issues but they are not big..

Thank you very much @psgs. This has also given me some great ideas to extend this style in to the rest of the site.

**Comment by psgs** [comment]
No problem @pjuu. Thanks for merging the pull request :smiley:

**Comment by pjuu** [comment]
:smile:

**Pull request merged**
