### PR TITLE
Ci docker build

### PR DESCRIPTION
**Pull request by docapotamus**

### CODE REVIEW

**Comment by docapotamus** [comment]
Apologies. There will be a lot of commits to this whilst I work it out.

Latest appears that the Python version isn't chaning `python` and it's still reverting to 2

**Comment by mcrmonkey** [comment]
Nice work this

:+1:

**Comment by docapotamus** [comment]
Cheers @mcrmonkey 

If your happy to squash merge this we can test it all out and ensure the Docker builds run

**Comment by mcrmonkey** [comment]
LGTM

**Pull request merged**
